[package]
name = "web"
version = "0.1.0"
authors = ["Roberto Vidal <vidal.roberto.j@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
r5rs = { path = ".." }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
wasm-bindgen = "=0.2.25"
